### ISSUE TITLE
Ice Cubes iOS: Multiple toots and replies to toots

### ISSUE THREAD

**Issue by electricbrick** [akirk/enable-mastodon-apps#14]
With the Ice Cubes auth (+IndieWeb  conflict?) issues behind us, posting from the Ice Cubes app as my site user is possible. However, there are about 10 separate toots being rendered out for the single toot I test-posted, and the reply to said test-toot from my standard user account also shows up about as many times.

![image](https://user-images.githubusercontent.com/2481417/232610054-9592ff5a-b2e1-4c99-9791-e5d7252f07ce.png)

![image](https://user-images.githubusercontent.com/2481417/232610093-f789ced6-aa6f-4808-beea-d6b6799bed60.jpeg)

**Comment by electricbrick** [comment]
Mastodon app behaves normally

![image](https://user-images.githubusercontent.com/2481417/232611419-3f554502-1840-49bc-8790-ba7703a77eaf.jpeg)

**Comment by electricbrick** [comment]
At second glance it also looks like there are some weird spacing output issues occurring, cross-app. I could be misperceiving that, might need to run some more tests.

![image](https://user-images.githubusercontent.com/2481417/232612330-9cf997c7-0c3a-46d3-9a21-a7ced90b681a.jpeg)

**Comment by huckabarry** [comment]
I have this same issue.
