### ISSUE TITLE
Connection-Issue with tootle (Linux)

### ISSUE THREAD

**Issue by dg9vh** [akirk/enable-mastodon-apps#15]
When trying to connect with tootle client under debian linux, the system-default browser opens and following error message is shown:
{"error":"invalid_client","error_description":"No client id supplied"}

Tootle meanwhile is waiting for an authorization-code:

![image](https://user-images.githubusercontent.com/13950650/233730062-30aa738f-5286-41bd-8c5c-6d91ed574d86.png)

**Comment by dg9vh** [comment]
Well yes, but I was not aware that it is discontinued... my fault.

Should we close this then?

**Comment by akirk** [comment]
Yes, let's close it. The error message that you shared looks like it didn't provide the necessary info to the server (it needs to choose its client_id).
