### ISSUE TITLE
Expose the application used to write the status

### ISSUE THREAD

**Issue by akirk** [akirk/enable-mastodon-apps#153]
The Mastodon API has support for [exposing the software that was used to write the status](https://docs.joinmastodon.org/entities/Status/#application) but it's not federated (https://github.com/mastodon/mastodon/issues/8476), so not worth implementing.

**Comment by pfefferle** [comment]
But it does not cost much and maybe gives a bit awareness to WordPress in the fediverse?!?

**Comment by akirk** [comment]
You would not see it anywhere. It's only displayed on your own Mastodon instance, which is your WordPress.
