### ISSUE TITLE
Feditext support

### ISSUE THREAD

**Issue by mediaformat** [akirk/enable-mastodon-apps#169]
Adding this to get the conversation happening between devs ;-)

Re: https://github.com/feditext/feditext/issues/394

**Comment by VyrCossont** [comment]
See my comment for details https://github.com/feditext/feditext/issues/394#issuecomment-2372612692 but there's a piece missing from the WP implementation of the v1 instance API.

**Comment by akirk** [comment]
I've released 0.9.6 [with your fix](https://github.com/akirk/enable-mastodon-apps/pull/171), @mediaformat, thank you! I don't have an iOS device to test, please tell me if it now works! Thanks!

**Comment by phillycodehound** [comment]
It looks like it works but with the Block Editor it sends things to a "Classic Block" which on some occasions makes the post throw random JSON or XML.

Is anyone else having this issue?

**Comment by akirk** [comment]
@phillycodehound Thanks for reporting. Please see #172.
