### ISSUE TITLE
Deleting toots in apps does not delete them in backend

### ISSUE THREAD

**Issue by knut-hildebrandt** [akirk/enable-mastodon-apps#17]
Tried to delete posts in Tusky and in Pinafore but without success. In both cases the post was not deleted in WP backend. In Pinafore did not happen nothing even though deletion was confirmed. In Tusky the toot at least disappeared from the timeline. Would have expected this in both apps and furthermore that it will be deleted in WP backend as well and thus won't appear nowhere anymore.

**Comment by huckabarry** [comment]
I have this same issue.

**Comment by akirk** [comment]
This should be fixed with 0.3.3, please test and tell me if it's fixed. Thank you!

**Comment by knut-hildebrandt** [comment]
Super, it worked in well in Pinafore and Tusky. I'm using now 0.3.4.

**Comment by knut-hildebrandt** [comment]
It worked fine in Fedilab, Pinafore and Tusky. Great, thanks.
