### ISSUE TITLE
Explore content rendering possibilities

### ISSUE THREAD

**Issue by mediaformat** [akirk/enable-mastodon-apps#172]
Currently all text posted via Mastodon apps gets added to a classic block, and is rendered as plain text: no links are made from urls, or hashtags, etc

Example: https://mediaformat.org/2024/09/this-post-was-made-using-the-official-mastodon-app/

**Comment by akirk** [comment]
Thanks! It looks like I was misremembering that I had implemented this already. [Images are added as blocks](https://github.com/akirk/enable-mastodon-apps/blob/main/includes/handler/class-status.php#L295) but paragraphs are not wrapped with a paragraph block. I'll implement it.

**Comment by akirk** [comment]
This should be fixed in 0.9.7 that I just released.
