### ISSUE TITLE
Plugin is causing an error when saving Widgets (evaluating 'e.endpoints')

### ISSUE THREAD

**Issue by lexpostma** [akirk/enable-mastodon-apps#178]
I have widgets on my WordPress site and include some shortcodes for Font Awesome (not sure if this is relevant). When I update a widget and want to save it, I’m getting the following error:
> There was an error. null is not an object (evaluating 'e.endpoints')

I tried several things, including WP Debug and disabling plugins one by one. Disabling “Enable Mastodon Apps” resolved the error, so I expect it might be caused by this plugin.

Hope you can resolve it. Please let me know how I can assist in finding the issue.

**Comment by lexpostma** [comment]
I’ve now tested this on a local WordPress install too. Getting a similar error with enabling this plugin:
> There was an error. null is not an object (evaluating 'preflightResponse.endpoints')
Again, the error is resolved when I disable “Enable Mastodon Apps”.

**Comment by akirk** [comment]
Sorry for the trouble, could you share a screenshot of the developer tools that show that error message so that the backtrace is visible? (a list of filenames)

**Comment by lexpostma** [comment]
I wish I knew how. The error shows in the WordPress UI, but not in the console. Here’s a screenshot and a screen recording.

<img width="1476" alt="Scherm­afbeelding 2024-10-08 om 18 57 55" src="https://github.com/user-attachments/assets/129ff68b-afef-4048-b9a6-d9f475663c8d">

After I reload, I clear the console and then click Update to trigger the error. No new messages show up in the console. This is in Safari, same happens in Firefox.

https://github.com/user-attachments/assets/b5364bc4-601b-45e3-92e1-aaf8a8bb035e

Is this what you meant? If not, please let me know what other dev tools I can pull up to assist.

**Comment by akirk** [comment]
I'm not sure I am familiar with that widget screen. Which theme do you use?

**Comment by lexpostma** [comment]
It’s my own custom theme, which is a fork from Twenty Twenty-Three. When I activate theme Twenty Twenty-Three version 1.5, the same happens.
