### ISSUE TITLE
Welcome Screen. Change the server? 

### ISSUE THREAD

**Issue by bph** [akirk/enable-mastodon-apps#187]
So now I am trying to wrap my head around the Mastodon Apps plugin. I have two mastodon accounts, one on `mastodon.social` and one on `twit.social`. On the Wecome screen I would like to add the `mastodon.social` server in the big box, as I think, that's what is asked of me, but it doesn't let me overwrite the `icodeforapurpose` default that's already in there. Where does it come from, and how can I override it? 
![Screenshot 2024-11-29 at 11 36 25](https://github.com/user-attachments/assets/34975ade-6142-4576-8fab-c32d022e605c)

**Comment by akirk** [comment]
The goal of the plugin is to make your WordPress compatible with Mastodon apps: they will talk to your own WordPress, you can see the posts of your friends (if you have the friends plugin), you can reply etc, all within the app.

The idea is to replace the need for a separate Mastodon account.

**Comment by akirk** [comment]
Thus you'll enter your own WordPress address in the Mastodon app of your choice and you will log in to your own WordPress through the app and access your own account.

**Comment by bph** [comment]
Oh wow, that's a big level of abstraction for my simple brain :-) I totally missed the whole idea of this plugin. 🤦‍♀️ What's the difference between a Mastodon app and a Mastodon server? So confused.

**Comment by akirk** [comment]
There is a list of apps in the readme, for example: https://github.com/akirk/enable-mastodon-apps?tab=readme-ov-file#description

**Comment by bph** [comment]
Thank you. As it's all working as intended, I close this issue
