### ISSUE TITLE
Specifying what CPT to use for new posts

### ISSUE THREAD

**Issue by jasontucker** [akirk/enable-mastodon-apps#25]
I'm curious if could you make it so you can specify what CPT a new post should use, having these show up as "posts" with a post format of status is nice but having them in a different CPT would work well for my needs. Any thoughts on this?

**Comment by akirk** [comment]
Certainly doable but I am worried about how to present the available custom post types since typically not all of the registered ones are suitable for being directly created. Would a filter that allows modifying the post to be inserted into the database be a viable solution for your use case?

**Comment by QurQuma** [comment]
I really need rhis too.
Thanks!

**Comment by akirk** [comment]
I just merged #154 which implements this.

**Comment by akirk** [comment]
Released in 0.9.4.
