### ISSUE TITLE
Remove Dependencies

### ISSUE THREAD

**Issue by pfefferle** [akirk/enable-mastodon-apps#46]
I would propose to remove all dependencies to third party plugins like ActivityPub and Friends and to focus on actions/filters, that can be then implemented by the Friends and ActivityPub plugin.

This would make the handling easier and provide a more solid base for others to build on top.

**Comment by akirk** [comment]
When developing this plugin, I tried to do this where possible. It works without either ActivityPub or Friends.

There are some places in the code where it checks for other plugins like this:
```
$status = make_clickable( $status );
if ( class_exists( '\Activitypub\Mention' ) ) {
	$status = \Activitypub\Mention::the_content( $status );
}
```

I need to review the code again but I introduced filters that other plugins can use, which I do in the Friends plugin. Do you have specific instances where you see I didn't adhere to this idea?
