### ISSUE TITLE
Open base dir restriction?

### ISSUE THREAD

**Issue by eiland-asbl** [akirk/enable-mastodon-apps#47]
I enabled the app, went to my endpoint and all I got:

Warning: file_exists(): open_basedir restriction in effect. File(/.htaccess) is not within the allowed path(s): (###) in /srv/###/wp-admin/includes/misc.php on line 278

in fact the whole setup was affected, the error log drowned with this message. With error reporting turned off, the plugin works reasonably well, but this is not acceptable.

**Comment by akirk** [comment]
Thanks for flagging but are you sure that the Enable Mastodon Apps plugin is causing it? There is no file_exists call or reference to htaccess in this code base.

**Comment by eiland-asbl** [comment]
Turned off my plugins one by one, and it turned out to be a conflict with ancient [slickquiz](https://github.com/jewlofthelotus/SlickQuiz-WordPress). Sorry!

**Comment by akirk** [comment]
Glad to hear! Thanks for following up with the solution!
