### ISSUE TITLE
ActivityPub V2 compatibility

### ISSUE THREAD

**Issue by toolstack** [akirk/enable-mastodon-apps#59]
ActivityPub V2 was just released and it looks like it breaks compatibility with this plugin as the timeline generates an "internal server error" on clients and you cannot connect a client.

**Comment by akirk** [comment]
Thank you for reporting and providing a fix!

**Comment by toolstack** [comment]
Np, I went to bed lastnight and everything was working and then work up to errors... thought I was going nuts till I noticed ActivityPub had been updated 😂
