### ISSUE TITLE
Images and Videos missing

### ISSUE THREAD

**Issue by thatguygriff** [akirk/enable-mastodon-apps#71]
Starting with 0.6.3 I noticed that images and videos on posts that were visible on the web were missing in Ivory and the default Mastodon app.

After some digging I traced it to [this change](https://github.com/akirk/enable-mastodon-apps/pull/55) and its removal of all Gutenberg tags also removing things like `wp:image`.

**Comment by akirk** [comment]
Sorry and thanks for tracing back the root cause! I'll release a fixed version.

**Comment by thatguygriff** [comment]
0.6.5 has restored images but any post with a <video> tag in it on the friends page is still missing the video in Mastodon apps. I haven't had a chance to dig into the why of this yet.
