### ISSUE TITLE
Add "generator" post meta for new posts

### ISSUE THREAD

**Issue by akirk** [akirk/enable-mastodon-apps#81]
Also then document how to use a filter to change the post type of new posts.

**Comment by Guanchishan** [comment]
Hello, does this issue relate to reading posts other than the default post type (custom post type)? 
If not, I apologize for the disturbance and will open a new issue. 
If it does, I suggest adding an option to this plugin to allow users to choose to include content from post types other than the default. 
This way, users can see the content from custom post types on their sites within the Mastodon apps. 
Moreover, it would be even better if toots sent via this plugin could select the post type their belong to!
Thank you for your hard work, developers. This plugin has become increasingly useful.

**Comment by akirk** [comment]
Thanks @Guanchishan. I can add this in #154.

**Comment by akirk** [comment]
Released in 0.9.4.
